In [64]:
import torch

In [65]:
def simple_tensor():
    """Returns a unit-value tensor with requires_grad=True."""
    return torch.tensor([1.0], requires_grad=True)

### Question 1

In [66]:
a = simple_tensor()
b = simple_tensor()

x = 2 * a + 3 * b
y = 5 * a**2 + 3 * b**3

z = 2 * x + 3 * y

z.backward()
a.grad

tensor([34.])

### Question 2

In [67]:
b = simple_tensor()
x = simple_tensor()
w = simple_tensor()

u = w * x
v = u + b
z = torch.relu(v)

z.backward(retain_graph=True)
w.grad

tensor([1.])

### Question 3

In [68]:
z = torch.sigmoid(v) # redefine z

w.grad.zero_()
z.backward()
w.grad

tensor([0.1050])

### Question 4

In [69]:
x = simple_tensor()

f = torch.exp(-x**2 - 2*x - torch.sin(x))
f.backward()

x.grad

tensor([-0.0974])

### Question 5

In [70]:
x = simple_tensor()
y = 8 * x**4 + 3 * x**3 + 7 * x**2 + 6 * x + 3
y.backward()
x.grad

tensor([61.])

### Question 6

In [82]:
x = simple_tensor()
y = simple_tensor()
z = simple_tensor()

f = torch.tanh(torch.log(1 + z * (2 * x) / torch.sin(y)))
f.backward()
y.grad, x.grad

(tensor([-0.1340]), tensor([0.2087]))

In [83]:
from math import *

x = y = z = 1

a = 2 * x
b = sin(y)
c = a / b
d = c * z
e = log(d + 1)
f = tanh(e)

print(a, b, c, d, e, f)

dfdy = (1 - tanh(e)**2) * (1 / (d + 1)) * z * (-a/b**2) * cos(y)
print('df / dy =', dfdy)

2 0.8414709848078965 2.3767902115562425 2.3767902115562425 1.21692561674831 0.8387449471877342
df / dy = -0.13400446514694908
