In [14]:
import torch
import numpy as np

### Question 1

In [2]:
T = torch.tensor([[1, 2], [3, 4]])

print(T.reshape(2 * 2))
print(torch.stack([T, T]))

tensor([1, 2, 3, 4])
tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])


In [3]:
x = torch.zeros(2, 1, 2)

print(x)
print(x.squeeze()) # remove dimensions with 1 element
print(x.unsqueeze(0)) # wrap dimension with parentheses

tensor([[[0., 0.]],

        [[0., 0.]]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[[[0., 0.]],

         [[0., 0.]]]])


### Question 2

In [4]:
torch.permute(T, (1, 0)) # (tensor, permutation of dimensions)

tensor([[1, 3],
        [2, 4]])

### Question 3

In [13]:
print(T[0][1]) # same as T[0, 1]
print(T[[0, 1]])

tensor(2)
tensor([[1, 2],
        [3, 4]])


### Question 4

In [16]:
T = torch.from_numpy(np.zeros(2))
T.numpy()

array([0., 0.])

### Question 5

In [18]:
torch.randint(1, 10, (7, 7))

tensor([[2, 4, 7, 7, 3, 9, 2],
        [3, 2, 6, 5, 5, 9, 2],
        [3, 6, 5, 6, 6, 5, 2],
        [2, 7, 4, 1, 4, 3, 7],
        [8, 8, 8, 3, 4, 7, 5],
        [6, 3, 7, 1, 8, 9, 3],
        [5, 3, 6, 4, 1, 7, 4]])

### Question 6

In [35]:
A = torch.randint(1, 10, (7, 7))
B = torch.randint(1, 10, (1, 7))

A @ B.T

tensor([[181],
        [198],
        [244],
        [168],
        [213],
        [191],
        [225]])

### Question 7

In [36]:
A = torch.rand((2, 3))
B = torch.rand((2, 3))

device = "cuda" if torch.cuda.is_available() else "cpu"

A = A.to(device)
B = B.to(device)

### Question 8

In [ ]:
A = torch.randint(1, 10, (7, 7))
B = torch.randint(1, 10, (1, 7))

A @ B.transpose(0, 1)

tensor([[223],
        [135],
        [180],
        [239],
        [164],
        [168],
        [140]])

### Question 9

In [41]:
print(A.min(), A.max())

tensor(1) tensor(9)


### Question 10

In [42]:
print(A.argmax(), A.argmin())

tensor(1) tensor(32)


### Question 11

In [45]:
torch.manual_seed(7)

shape = (1, 1, 1, 10)
T1 = torch.rand(shape)
T2 = T1.squeeze()

print(T1, T1.shape)
print(T2, T2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
