In [3]:
import torch

### Question 1

In [4]:
T = torch.tensor([[1, 2], [3, 4]])

print(T.reshape(2 * 2))
print(torch.stack([T, T]))

tensor([1, 2, 3, 4])
tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])


In [7]:
x = torch.zeros(2, 1, 2)

print(x)
print(x.squeeze()) # remove dimensions with 1 element
print(x.unsqueeze(0)) # wrap dimension with parentheses

tensor([[[0., 0.]],

        [[0., 0.]]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[[[0., 0.]],

         [[0., 0.]]]])


### Question 2

In [10]:
torch.permute(T, (1, 0)) # (tensor, permutation of dimensions)

tensor([[1, 3],
        [2, 4]])

### Question 3

In [ ]:
T[0]