In [2]:
import torch
torch.__version__

'2.5.1'

In [3]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.item())

tensor(7)
7


In [4]:
tensor = torch.tensor((
    (7, 8),
    (9, 10)
))

print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

tensor([[ 7,  8],
        [ 9, 10]])
torch.Size([2, 2])
2
torch.int64


In [5]:
random_tensor = torch.rand(size=(3, 4))
zeros = torch.zeros(size=(3, 4))
ones = torch.ones_like(zeros)

In [6]:
A = torch.tensor((
    (1, 2),
    (3, 4)
))

B = torch.tensor((5, 10))

A @ B # matrix multiplication

tensor([25, 55])

In [7]:
print(torch.cuda.is_available())
print(torch.cuda.device_count())

False
0


In [8]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

# device = 'gpu' if torch.cuda.is_available() else 'cpu'
# tensor_on_gpu = tensor.to(device)
# tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

tensor([1, 2, 3]) cpu
